apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rag6-aug14-1-gitops
  description: This is GitOps manifest for rag6-aug14-1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rag6-aug14-1
    janus-idp.io/tekton: rag6-aug14-1 
    backstage.io/kubernetes-id: rag6-aug14-1 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rag6-aug14-1
